name: TypeScript Check

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Install Dependencies
      run: npm ci
      
    - name: TypeScript Check
      run: npm run tsc -- --noEmit
